### ISSUE TITLE
pep8ify indents top level comments

### ISSUE THREAD

**Issue by alex** [spulec/pep8ify#16]
I don't believe it should do so, the following code is perfectly fine:

``` py
import foo

# a comment

foo.bar()
```

but `pep8ify` emits the following diff:

``` diff
--- t.py    (original)
+++ t.py    (refactored)
@@ -1,5 +1,4 @@
 import foo
-
-# a comment
+  # a comment

 foo.bar()
```

**Comment by spulec** [comment]
Thanks Alex. This was a regression caused by 904e380a58be5af77999e8fe5206a8019c8aa538.

I'm going to do a bit more code cleanup, but plan on pushing out a new version later today.
