### ISSUE TITLE
Pep8ify wants to remove a space before \

### ISSUE THREAD

**Issue by PaulMcMillan** [spulec/pep8ify#9]
I dislike line continuations with `\` as much as the next guy, but pep8ify seems to be proposing an unwarranted change to my codebase:

```
foo = \
    'some long stuff'
```

is being corrected to

```
foo =\
    'some long stuff'
```

Which looks weird to my eye. It feels like pep8ify should leave those lines alone.

**Comment by spulec** [comment]
I agree that what it is doing in your situation seems wrong.

I imagine you would agree that this correction below is correct:

``` python
x = (a + 
     b)
```

should be changed to

``` python
x = (a +
     b)
```

(There is a trailing space in the first one)

In the middle is the following situation:

``` python
x = a + \
    b
```

Should pep8ify treat this different than the situation above?

pep8 apparently will not even complain about

``` python
x = a +      \
    b
```

I'm not sure where this leaves us. We can special-case explicit line joining with backslashes to be different than  implicit line joining with parens/braces, but that seems wrong to me. On the other hand, I don't like pep8ify changing things that pep8 doesn't complain about, even if I think that pep8 is wrong. I probably need to get more involved in that project.

Thoughts?

**Comment by PaulMcMillan** [comment]
I think the issue is that pep8ify is treating the `\` as the literal end of line, when in fact, we're visually processing it as a character and expecting the normal spacing rules around operators for a character.

As you said, the first example should remove the trailing space, and I'd prefer the last example tightened that extra space up to a single space even if pep8 doesn't complain about it.

On some level, I think it's ok for pep8ify to be slightly more opinionated than pep8 itself, since it has to make a call about how to fix a violation, and while it's making that decision, it makes sense to normalize the rest of the file too.
